# Generated by Django 4.2.19 on 2025-02-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customproduct',
            name='design_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
