# Generated by Django 4.2.19 on 2025-02-12 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_order_delivered_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivered_date',
        ),
    ]
