# Generated by Django 4.2.19 on 2025-02-12 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0003_parentcategory_alter_product_subcategory_and_more'),
        ('customer', '0011_order_delivered_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('invoice_date', models.DateField()),
                ('invoice_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_file', models.URLField(blank=True, null=True)),
                ('warranty_plan', models.CharField(choices=[('799_1yr', '799 AED - 1 year'), ('999_2yr', '999 AED - 2 years'), ('1799_5yr', '1799 AED - 5 years')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranty_registrations', to='products_app.product')),
            ],
        ),
    ]
