# Generated by Django 4.2.19 on 2025-02-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_remove_warrantyregistration_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantyregistration',
            name='warranty_number',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True),
        ),
    ]
