# Generated by Django 4.2.19 on 2025-02-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_warrantyregistration_warranty_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimWarranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warranty_number', models.CharField(max_length=8, unique=True)),
                ('description', models.TextField()),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('response', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
