# Generated by Django 4.2.19 on 2025-02-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_alter_cart_customer_alter_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='custom_product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='custom_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='custom_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='design_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size_unit',
            field=models.CharField(choices=[('inches', 'Inches'), ('feet', 'Feet')], default='inches', max_length=10),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='CustomProduct',
        ),
    ]
