# Generated by Django 4.2.19 on 2025-02-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_remove_cartitem_custom_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_items',
        ),
    ]
