# Generated by Django 4.2.19 on 2025-02-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_order_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_address',
            old_name='landmark',
            new_name='address_line1',
        ),
        migrations.RenameField(
            model_name='customer_address',
            old_name='street_address',
            new_name='address_line2',
        ),
        migrations.RenameField(
            model_name='customer_address',
            old_name='building_name',
            new_name='company_name',
        ),
        migrations.RenameField(
            model_name='customer_address',
            old_name='district',
            new_name='ext',
        ),
        migrations.RemoveField(
            model_name='customer_address',
            name='delivery_instructions',
        ),
        migrations.AddField(
            model_name='customer_address',
            name='country',
            field=models.CharField(blank=True, choices=[('UAE', 'UAE'), ('OMAN', 'OMAN'), ('SAUDI ARABIA', 'SAUDI ARABIA'), ('Bahrain', 'Bahrain'), ('Kuwait', 'Kuwait')], max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customer_address',
            name='state',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='customer_address',
            name='zip_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer_address',
            name='city',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
