# Generated by Django 4.2.19 on 2025-02-13 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0010_remove_product_installation_product_and_more'),
        ('customer', '0022_rename_landmark_customer_address_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyregistration',
            name='invoice_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products_app.warranty_plan'),
        ),
    ]
