# Generated by Django 4.2.19 on 2025-02-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_alter_warrantyregistration_invoice_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warrantyregistration',
            name='warranty_plan',
        ),
        migrations.AddField(
            model_name='warrantyregistration',
            name='warranty_plan_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
