# Generated by Django 4.2.19 on 2025-02-13 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0024_remove_warrantyregistration_warranty_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_address',
            name='country',
            field=models.CharField(blank=True, choices=[('UAE', 'UAE'), ('Oman', 'OMAN'), ('Bahrain', 'BAHRAIN'), ('Qatar', 'QATAR'), ('Saudi Arabia', 'SAUDI ARABIA'), ('Kuwait', 'KUWAIT')], max_length=500, null=True),
        ),
    ]
