# Generated by Django 4.2.19 on 2025-02-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_alter_customer_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(blank=True, choices=[('lead', 'LEAD'), ('client', 'CLIENT')], default='lead', max_length=300, null=True),
        ),
    ]
