# Generated by Django 4.2.19 on 2025-02-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_alter_order_delivered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
