# Generated by Django 5.1.4 on 2025-02-18 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_order_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warrantyregistration',
            old_name='product_name',
            new_name='invoice_number',
        ),
    ]
