# Generated by Django 5.1.4 on 2025-02-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0029_rename_product_name_warrantyregistration_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='higher_designer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
