# Generated by Django 5.1.4 on 2025-02-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0030_order_higher_designer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='higher_designer',
        ),
        migrations.AddField(
            model_name='cart',
            name='higher_designer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
