# Generated by Django 5.1.4 on 2025-02-24 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0031_remove_order_higher_designer_cart_higher_designer'),
        ('products_app', '0018_designer_rate_rate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='design_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='hire_designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products_app.designer_rate'),
        ),
    ]
