# Generated by Django 5.1.4 on 2025-02-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0032_cartitem_design_description_cartitem_hire_designer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyregistration',
            name='warranty_number',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
