# Generated by Django 5.1.4 on 2025-02-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0034_banner_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner_Image',
        ),
    ]
