# Generated by Django 5.1.4 on 2025-02-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0036_otprecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimwarranty',
            name='warranty_number',
            field=models.CharField(max_length=8),
        ),
    ]
