# Generated by Django 5.1.4 on 2025-02-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0037_alter_claimwarranty_warranty_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='site_visit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='higher_designer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='site_visit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
