# Generated by Django 5.1.4 on 2025-02-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0038_cart_site_visit_order_higher_designer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='site_visit_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
