# Generated by Django 5.1.4 on 2025-02-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0039_order_site_visit_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vat_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='vat_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
