# Generated by Django 5.1.4 on 2025-03-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0041_alter_order_delivered_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='higher_designer',
        ),
    ]
