# Generated by Django 5.1.4 on 2025-03-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0042_remove_order_higher_designer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='size_unit',
            field=models.CharField(choices=[('centimeter', 'Centimeter'), ('inches', 'Inches'), ('feet', 'Feet')], default='centimeter', max_length=10),
        ),
    ]
