# Generated by Django 5.1.4 on 2025-03-06 06:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0044_alter_cartitem_size_unit'),
        ('products_app', '0032_alter_standard_sizes_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDesign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymous_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('product_name', models.CharField(blank=True, max_length=900, null=True)),
                ('product_min_width', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('product_min_height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('product_max_width', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('product_max_height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_image', models.URLField(blank=True, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(choices=[('cm', 'Centimeter'), ('inches', 'Inches'), ('feet', 'Feet'), ('yard', 'Yard'), ('meter', 'Meter'), ('mm', 'Millimeter')], default='cm', max_length=10)),
                ('design_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products_app.product')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('customer__isnull', False), ('anonymous_uuid__isnull', False), _connector='OR'), name='customer_or_anon_uuid_required')],
            },
        ),
    ]
