# Generated by Django 5.1.4 on 2025-03-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0045_customerdesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdesign',
            name='design_image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
