# Generated by Django 5.1.4 on 2025-03-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0048_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_user',
            name='status',
            field=models.CharField(blank=True, choices=[('lead', 'LEAD'), ('client', 'CLIENT')], default='client', max_length=300, null=True),
        ),
    ]
