# Generated by Django 5.1.4 on 2025-03-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0051_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='verified_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='verified_mobile',
            field=models.BooleanField(default=False),
        ),
    ]
