# Generated by Django 5.1.4 on 2025-03-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0052_customer_verified_email_customer_verified_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='verified_email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='verified_mobile',
        ),
    ]
