# Generated by Django 5.1.4 on 2025-03-17 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0055_customer_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprecord',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
