# Generated by Django 5.1.7 on 2025-03-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0059_otprecord_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprecord',
            name='otp_for',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('mobile', 'Mobile')], default='email', max_length=20, null=True),
        ),
    ]
