# Generated by Django 5.1.7 on 2025-03-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0060_otprecord_otp_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprecord',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
