# Generated by Django 5.1.7 on 2025-04-03 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('customer', '0062_passwordresetsession_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='delivery_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_cart_items', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='delivery_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='distance_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distance_cart_items', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='distance_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='installation_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installation_cart_items', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='installation_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='thickness_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thickness_cart_items', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='thickness_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='turnaround_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnaround_cart_items', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='turnaround_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
