# Generated by Django 5.1.7 on 2025-04-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0063_cartitem_delivery_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_smart',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
