# Generated by Django 5.1.7 on 2025-04-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0064_cartitem_is_smart'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_user',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
