# Generated by Django 5.1.7 on 2025-04-03 09:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0065_client_user_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client_user',
            new_name='RequestedEmailUsers',
        ),
        migrations.AlterModelTable(
            name='requestedemailusers',
            table='customer_client_user',
        ),
    ]
