# Generated by Django 5.1.7 on 2025-04-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0066_rename_client_user_requestedemailusers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedemailusers',
            name='type',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('download', 'Download'), ('print', 'Print')], default='email', max_length=300, null=True),
        ),
    ]
