# Generated by Django 5.1.7 on 2025-04-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0067_requestedemailusers_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(blank=True, choices=[('lead', 'LEAD'), ('client', 'CLIENT'), ('data', 'Data')], default='lead', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='requestedemailusers',
            name='status',
            field=models.CharField(blank=True, choices=[('lead', 'LEAD'), ('client', 'CLIENT'), ('data', 'Data')], default='client', max_length=300, null=True),
        ),
    ]
