# Generated by Django 4.2.19 on 2025-02-12 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0003_parentcategory_alter_product_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard_sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_sizes', models.CharField(blank=True, max_length=200, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standard_sizes', to='products_app.product')),
            ],
        ),
    ]
