# Generated by Django 4.2.19 on 2025-02-12 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0004_standard_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='standard_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='width',
        ),
    ]
