# Generated by Django 4.2.19 on 2025-02-13 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0007_warranty_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard_sizes',
            name='standard_sizes',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
