# Generated by Django 4.2.19 on 2025-02-13 12:50

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0008_alter_standard_sizes_standard_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_overview',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
