# Generated by Django 4.2.19 on 2025-02-13 12:56

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0009_product_product_overview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_installation',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product_overview',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product_specifications',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='installation',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_specifications',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Installation_steps',
        ),
        migrations.DeleteModel(
            name='Product_installation',
        ),
        migrations.DeleteModel(
            name='Product_overview',
        ),
        migrations.DeleteModel(
            name='Product_specifications',
        ),
    ]
