# Generated by Django 5.1.4 on 2025-02-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0013_remove_category_parent_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Higher_designer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designer_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
