# Generated by Django 5.1.4 on 2025-02-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0014_higher_designer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Offer_slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_details', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
