# Generated by Django 5.1.4 on 2025-02-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0015_product_offer_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designer_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
