# Generated by Django 5.1.4 on 2025-02-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0016_designer_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designer_rate',
            name='hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
