# Generated by Django 5.1.4 on 2025-02-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0017_alter_designer_rate_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer_rate',
            name='rate_type',
            field=models.CharField(choices=[('hour', 'Per Hour'), ('day', 'Per Day'), ('week', 'Per Week'), ('month', 'Per Month')], default='hour', max_length=10),
        ),
    ]
