# Generated by Django 5.1.4 on 2025-02-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0018_designer_rate_rate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parentcategory',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
