# Generated by Django 5.1.4 on 2025-02-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0022_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('centimeter', 'Centimeter'), ('inches', 'Inches'), ('feet', 'Feet')], default='centimeter', max_length=100, null=True),
        ),
    ]
