# Generated by Django 5.1.4 on 2025-02-28 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0023_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='max_height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum height (cm)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='max_width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum width (cm)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='min_height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum height (cm)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='min_width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum width (cm)', max_digits=6, null=True),
        ),
    ]
