# Generated by Django 5.1.4 on 2025-02-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0024_product_max_height_product_max_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('centimeter', 'Centimeter')], default='centimeter', help_text='🛠 Select the measurement unit', max_length=100, null=True),
        ),
    ]
