# Generated by Django 5.1.4 on 2025-03-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0030_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_height',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='📐 Maximum height', max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_width',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='📏 Maximum width', max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_height',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='📐 Minimum height', max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_width',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='📏 Minimum width', max_digits=6),
        ),
    ]
