# Generated by Django 5.1.4 on 2025-03-05 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0031_alter_product_max_height_alter_product_max_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard_sizes',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standard_sizes', to='products_app.product', verbose_name='Product'),
        ),
    ]
