# Generated by Django 5.1.4 on 2025-03-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0033_customuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amazon_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
