# Generated by Django 5.1.4 on 2025-03-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0034_product_amazon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='standard_sizes',
            name='unit',
            field=models.CharField(choices=[('cm', 'Centimeter'), ('inches', 'Inches'), ('feet', 'Feet'), ('yard', 'Yard'), ('meter', 'Meter'), ('mm', 'Millimeter')], default='cm', help_text='🛠 Select the measurement unit', max_length=100),
        ),
    ]
