# Generated by Django 5.1.4 on 2025-03-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0035_standard_sizes_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_direct_add_to_cart',
            field=models.BooleanField(blank=True, default=False, help_text='Allow Direct Add to Cart (Without Customization)', null=True),
        ),
    ]
