# Generated by Django 5.1.7 on 2025-03-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0041_rename_price_product_variable_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variable_price',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='💰 This is the variable price based on size and customization.', max_digits=10, null=True),
        ),
    ]
