# Generated by Django 5.1.7 on 2025-03-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0042_remove_product_variable_price_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fixed_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='💰 This is the variable price based on size and customization.', max_digits=16, null=True),
        ),
    ]
