# Generated by Django 5.1.7 on 2025-03-31 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0043_alter_product_fixed_price_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Pickup, FastTrack, Express, Standard', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_decimal', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='products_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.CharField(help_text='Example: 20 km, 50 km, Below 100 km', max_length=50)),
                ('unit', models.CharField(choices=[('km', 'Kilometers'), ('miles', 'Miles')], default='km', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_decimal', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances', to='products_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='InstallationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: 5 business days, 8 business days', max_length=50)),
                ('days', models.IntegerField(help_text='Number of business days for installation')),
                ('description', models.TextField(blank=True, null=True)),
                ('price_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_decimal', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installation_types', to='products_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Thickness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(help_text='Example: 12mm, 1.5cm, etc.', max_length=50)),
                ('price', models.DecimalField(decimal_places=6, help_text='Price per unit', max_digits=16)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thicknesses', to='products_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='TurnaroundTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Standard, Express, FastTrack', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Price increase in percentage (e.g., 10 for 10%)', max_digits=5, null=True)),
                ('price_decimal', models.DecimalField(blank=True, decimal_places=6, help_text='Price increase in fixed decimal value', max_digits=16, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnaround_times', to='products_app.product')),
            ],
        ),
    ]
