# Generated by Django 5.1.7 on 2025-03-31 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0044_delivery_distance_installationtype_thickness_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Pickup, FastTrack, Express, Standard', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_decimal', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Global Delivery Options',
                'ordering': ['price_decimal'],
            },
        ),
        migrations.CreateModel(
            name='GlobalDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.CharField(help_text='Example: 20 km, 50 km, Below 100 km', max_length=50)),
                ('unit', models.CharField(choices=[('km', 'Kilometers'), ('miles', 'Miles')], default='km', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_decimal', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Global Distance Options',
                'ordering': ['price_decimal'],
            },
        ),
        migrations.CreateModel(
            name='GlobalInstallationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: 5 business days, 8 business days', max_length=50)),
                ('days', models.IntegerField(help_text='Number of business days for installation')),
                ('description', models.TextField(blank=True, null=True)),
                ('price_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_decimal', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Global Installation Options',
                'ordering': ['days'],
            },
        ),
        migrations.CreateModel(
            name='GlobalThickness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(help_text='Example: 12mm, 1.5cm, etc.', max_length=50)),
                ('price', models.DecimalField(decimal_places=6, help_text='Price per unit', max_digits=16)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this option is active')),
            ],
            options={
                'verbose_name_plural': 'Global Thickness Options',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='GlobalTurnaroundTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Example: Standard, Express, FastTrack', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_decimal', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Global Turnaround Time Options',
                'ordering': ['price_decimal'],
            },
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['price_decimal'], 'verbose_name_plural': 'Product Delivery Options'},
        ),
        migrations.AlterModelOptions(
            name='distance',
            options={'ordering': ['price_decimal'], 'verbose_name_plural': 'Product Distance Options'},
        ),
        migrations.AlterModelOptions(
            name='installationtype',
            options={'ordering': ['days'], 'verbose_name_plural': 'Product Installation Options'},
        ),
        migrations.AlterModelOptions(
            name='thickness',
            options={'ordering': ['price'], 'verbose_name_plural': 'Product Thickness Options'},
        ),
        migrations.AlterModelOptions(
            name='turnaroundtime',
            options={'ordering': ['price_decimal'], 'verbose_name_plural': 'Product Turnaround Time Options'},
        ),
        migrations.AlterField(
            model_name='turnaroundtime',
            name='price_decimal',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='turnaroundtime',
            name='price_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
