# Generated by Django 5.1.7 on 2025-04-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0045_globaldelivery_globaldistance_globalinstallationtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalthickness',
            name='price_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='thickness',
            name='price_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
