# Generated by Django 5.1.7 on 2025-05-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0046_globalthickness_price_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alternate_names',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
