# Generated by Django 5.2.8 on 2025-11-14 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0049_inventorystock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_tiered',
            field=models.BooleanField(blank=True, default=False, help_text='Enable tier pricing for this product', null=True),
        ),
        migrations.CreateModel(
            name='ProductTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_level', models.PositiveIntegerField(choices=[(1, 'Tier 1'), (2, 'Tier 2'), (3, 'Tier 3')])),
                ('start_quantity', models.PositiveIntegerField(help_text='Starting quantity for this tier')),
                ('end_quantity', models.PositiveIntegerField(help_text='Ending quantity for this tier')),
                ('price', models.DecimalField(decimal_places=6, help_text='Price per unit for this quantity range', max_digits=16)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='products_app.product')),
            ],
            options={
                'ordering': ['tier_level'],
                'unique_together': {('product', 'tier_level')},
            },
        ),
    ]
