# Generated by Django 5.1.4 on 2025-03-18 07:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pep_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='custom_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
