# Generated by Django 5.1.4 on 2025-03-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pep_app', '0002_alter_contactlist_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
    ]
