# Generated by Django 5.1.7 on 2025-03-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pep_app', '0003_placeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
