# Generated by Django 5.1.4 on 2025-03-19 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pep_app', '0003_partners_mobile_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='pep_app.partners'),
        ),
    ]
