# Generated by Django 5.1.7 on 2025-03-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pep_app', '0004_emailtemplate_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
