# Generated by Django 5.1.4 on 2025-03-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pep_app', '0004_alter_contact_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='account',
        ),
        migrations.AddField(
            model_name='contact',
            name='account',
            field=models.ManyToManyField(blank=True, to='pep_app.accounts'),
        ),
    ]
