# Generated by Django 5.1.7 on 2025-03-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pep_app', '0005_emailcampaign_sender_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
