# Generated by Django 5.1.7 on 2025-03-21 13:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pep_app', '0006_alter_emailcampaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='total_recipients',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('opened', 'Opened'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pep_app.emailcampaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pep_app.contact')),
            ],
        ),
    ]
