# Generated by Django 5.1.7 on 2025-04-01 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pep_app', '0007_emailtemplate_sent_at_emailtemplate_total_recipients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeholder',
            name='value',
        ),
    ]
