# Generated by Django 5.1.7 on 2025-04-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pep_app', '0008_remove_placeholder_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='status',
            field=models.CharField(blank=True, choices=[('data', 'Data'), ('lead', 'Lead'), ('client', 'Client'), ('unsubscribed', 'Unsubscribed'), ('prospect', 'Prospect')], default='data', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('data', 'Data'), ('lead', 'Lead'), ('client', 'Client'), ('unsubscribed', 'Unsubscribed'), ('prospect', 'Prospect')], default='data', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailrecipient',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('link', 'Link Clicked'), ('unsubscribed', 'Unsubscribed'), ('opened', 'Opened'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
