# Generated by Django 5.1.7 on 2025-04-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pep_app', '0009_alter_accounts_status_alter_contact_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaignAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Email Campaign Analytics',
                'verbose_name_plural': 'Email Campaign Analytics',
            },
        ),
    ]
