# Generated by Django 5.1.7 on 2025-04-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pep_app', '0010_emailcampaignanalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email_verification_status',
            field=models.CharField(blank=True, help_text='Stores the verification result from Clearout API as a JSON string', max_length=1000, null=True),
        ),
    ]
