# Generated by Django 5.1.7 on 2025-04-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pep_app', '0011_contact_email_verification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='selected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='selected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
