# Generated by Django 5.1.7 on 2025-04-25 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pep_app', '0012_emailcampaign_selected_emailtemplate_selected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email_verification_status',
            new_name='email_deliverability',
        ),
    ]
