# Generated by Django 5.1.7 on 2025-04-25 07:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pep_app', '0013_rename_email_verification_status_contact_email_deliverability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCronJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('cron_expression', models.CharField(help_text="Cron expression in UTC (e.g., '0 0 * * *' for daily at midnight)", max_length=100)),
                ('frequency', models.CharField(choices=[('minutes', 'Minutes'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('specific_date', 'Specific Date')], default='daily', max_length=20)),
                ('start_time', models.DateTimeField(help_text='Start time in UTC')),
                ('end_time', models.DateTimeField(blank=True, help_text='End time in UTC (leave blank for no end)', null=True)),
                ('specific_date', models.DateField(blank=True, help_text='Specific date for one-time execution', null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaigns', models.ManyToManyField(blank=True, related_name='cron_jobs', to='pep_app.emailcampaign')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cron_jobs', to=settings.AUTH_USER_MODEL)),
                ('email_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cron_jobs', to='pep_app.emailtemplatecategory')),
                ('email_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cron_jobs', to='pep_app.emailtemplate')),
                ('partner', models.ForeignKey(blank=True, help_text='If set, only check contacts from this partner', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cron_jobs', to='pep_app.partners')),
            ],
            options={
                'verbose_name': 'Email Cron Job',
                'verbose_name_plural': 'Email Cron Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CronJobExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('execution_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('no_contacts', 'No Contacts Found')], default='success', max_length=20)),
                ('contacts_found', models.IntegerField(default=0)),
                ('emails_sent', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cron_executions', to='pep_app.emailcampaign')),
                ('cron_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='pep_app.emailcronjob')),
            ],
            options={
                'ordering': ['-execution_time'],
            },
        ),
    ]
