# Generated by Django 5.1.7 on 2025-04-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pep_app', '0014_emailcronjob_cronjobexecution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcronjob',
            name='partner',
        ),
        migrations.AlterField(
            model_name='emailcronjob',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Start time in UTC (defaults to creation time if not provided)', null=True),
        ),
    ]
