# Generated by Django 5.1.7 on 2025-04-25 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pep_app', '0015_remove_emailcronjob_partner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcronjob',
            name='email_category',
        ),
        migrations.AlterField(
            model_name='emailcronjob',
            name='campaigns',
            field=models.ManyToManyField(related_name='cron_jobs', to='pep_app.emailcampaign'),
        ),
        migrations.AlterField(
            model_name='emailcronjob',
            name='cron_expression',
            field=models.CharField(blank=True, help_text="Cron expression in UTC (e.g., '0 0 * * *' for daily at midnight)", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='emailcronjob',
            name='email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cron_jobs', to='pep_app.emailtemplate'),
        ),
    ]
