# Generated by Django 5.1.7 on 2025-04-25 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pep_app', '0016_remove_emailcronjob_email_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcronjob',
            name='cron_expression',
        ),
        migrations.RemoveField(
            model_name='emailcronjob',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='emailcronjob',
            name='start_time',
        ),
        migrations.AddField(
            model_name='emailcronjob',
            name='cron_time',
            field=models.TimeField(blank=True, help_text='Time of day to run the cron job in 24-hour UTC format (e.g., 14:30 for 2:30 PM UTC).', null=True),
        ),
        migrations.AddField(
            model_name='emailcronjob',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='End date and time in UTC. Leave blank for no expiration (repeats indefinitely).', null=True),
        ),
        migrations.AddField(
            model_name='emailcronjob',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Start date and time in UTC. Defaults to creation date if not provided.', null=True),
        ),
        migrations.AlterField(
            model_name='emailcronjob',
            name='created_by',
            field=models.ForeignKey(help_text='User who created the cron job. Defaults to the current user if not specified.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cron_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailcronjob',
            name='email_template',
            field=models.ForeignKey(blank=True, help_text='Select the email template to use for campaigns triggered by this cron job', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cron_jobs', to='pep_app.emailtemplate'),
        ),
        migrations.AlterField(
            model_name='emailcronjob',
            name='frequency',
            field=models.CharField(choices=[('minutes', 'Minutes'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('specific_date', 'Specific Date')], default='daily', help_text="How often the cron job should run. Choose 'Specific Date' for one-time execution.", max_length=20),
        ),
        migrations.AlterField(
            model_name='emailcronjob',
            name='name',
            field=models.CharField(help_text='Name of the cron job for identification', max_length=255),
        ),
        migrations.AlterField(
            model_name='emailcronjob',
            name='specific_date',
            field=models.DateField(blank=True, help_text="Specific date for one-time execution. Used only if frequency is 'Specific Date'.", null=True),
        ),
        migrations.AlterField(
            model_name='emailcronjob',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], default='active', help_text='Current status of the cron job', max_length=20),
        ),
    ]
