# Generated by Django 5.1.7 on 2025-04-25 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pep_app', '0017_remove_emailcronjob_cron_expression_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcronjob',
            name='specific_date',
        ),
        migrations.AlterField(
            model_name='emailcronjob',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created the cron job. Automatically set to the current user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cron_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emailcronjob',
            name='cron_time',
            field=models.TimeField(blank=True, help_text='Time of day to run the cron job in 24-hour UTC format (e.g., 14:30 for 2:30 PM UTC). Enter time manually or use the time picker.', null=True),
        ),
        migrations.AlterField(
            model_name='emailcronjob',
            name='end_date',
            field=models.DateField(blank=True, help_text="End date in UTC. Leave blank for no expiration (repeats indefinitely). Not applicable for 'Specific Date' frequency.", null=True),
        ),
        migrations.AlterField(
            model_name='emailcronjob',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date in UTC. Defaults to creation date if not provided.', null=True),
        ),
    ]
