# Generated by Django 5.1.7 on 2025-04-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pep_app', '0019_remove_emailcronjob_cron_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcronjob',
            name='end_date',
            field=models.DateField(blank=True, help_text='End date in UTC. Cron job will stop running after this date.', null=True),
        ),
        migrations.AlterField(
            model_name='emailcronjob',
            name='start_date',
            field=models.DateField(blank=True, help_text='Start date in UTC. Cron job will start checking for contacts from this date.', null=True),
        ),
    ]
