# Generated by Django 5.1.7 on 2025-04-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pep_app', '0020_alter_emailcronjob_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcronjob',
            name='partner',
        ),
        migrations.AddField(
            model_name='emailcronjob',
            name='partners',
            field=models.ManyToManyField(blank=True, help_text='Partners associated with this cron job (automatically determined from contacts)', related_name='email_cron_jobs', to='pep_app.partners'),
        ),
        migrations.AlterField(
            model_name='emailcronjob',
            name='campaigns',
            field=models.ManyToManyField(blank=True, related_name='cron_jobs', to='pep_app.emailcampaign'),
        ),
    ]
