# Generated by Django 5.1.7 on 2025-04-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pep_app', '0021_remove_emailcronjob_partner_emailcronjob_partners_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjobexecution',
            name='new_contacts_processed',
            field=models.ManyToManyField(blank=True, help_text='New contacts processed in this execution', related_name='processed_in_executions', to='pep_app.contact'),
        ),
        migrations.AddField(
            model_name='emailcronjob',
            name='contact_lists',
            field=models.ManyToManyField(blank=True, help_text='Contact lists to include in this cron job', related_name='email_cron_jobs', to='pep_app.contactlist'),
        ),
        migrations.AddField(
            model_name='emailcronjob',
            name='cron_expression',
            field=models.CharField(blank=True, help_text="Custom cron expression (e.g., '0 7 * * *' for daily at 7 AM)", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emailcronjob',
            name='frequency',
            field=models.CharField(choices=[('minutes', 'Minutes'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('specific_date', 'Specific Date')], default='daily', help_text='Frequency of the cron job execution', max_length=20),
        ),
        migrations.AddField(
            model_name='emailcronjob',
            name='processed_contacts',
            field=models.ManyToManyField(blank=True, help_text='Contacts that have already been processed by this cron job', related_name='processed_by_cron_jobs', to='pep_app.contact'),
        ),
    ]
