# Generated by Django 5.1.7 on 2025-04-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pep_app', '0022_cronjobexecution_new_contacts_processed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailcronjob',
            name='cron_expression',
        ),
        migrations.RemoveField(
            model_name='emailcronjob',
            name='email_category',
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='delivery_status',
            field=models.CharField(choices=[('queued', 'Queued'), ('campaign_sent', 'Campaign Sent')], default='queued', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailcronjob',
            name='frequency',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='daily', help_text='Frequency of the cron job execution', max_length=20),
        ),
    ]
